### ISSUE TITLE
EPIC - CRUD COMPANY

### ISSUE THREAD

**Issue by thomaspiu** [thomaspiu/Ebisu#2]
- [ ] As a Ebisu Administrator, I can CRUD a company ;
- [ ] As a Ebisu Administrator, I can link one or more users to a company ;
- [ ] As a Ebisu Administrator, I can link a user to one company ;
