### ISSUE TITLE
EPIC - CRUD TEAM

### ISSUE THREAD

**Issue by thomaspiu** [thomaspiu/Ebisu#3]
USER SPEC : 
TECHNICAL SPEC : 

- [ ] As a EBISU Administator, I want to be able to CRUD a Team from a company ;
- [ ] As a EBISU Administator, I want to add one or more users to a team ;
- [ ] As a EBISU Administator, I want to add link a user to one or more team ;
